[package]
name = "chess_bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
owlchess = "0.1.0"
chess = "3.2.0"
shakmaty = "0.21.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "main"
harness = false

[lib]
bench = false
